<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="css/style.css">
  <title>Hôtellerie</title>
</head>
<body>
  <header class="bg-secondary p-3 text-center mb-5">
    <a href="index.php"><h1>Bienvenue sur notre site</h1></a>
    <nav class="navbar navbar-dark">
      <!-- ADMIN & RECEPTIONNISTE -->
      <a class="text-white" href="?action=connexion&action2=valeur2">Se connecter </a>
      <a class="text-white" href="">Se déconnecter </a>
      <a class="text-white" href="">Toutes les réservations </a>
      <!-- ADMIN -->
      <a class="text-white" href="index.php?action=ajouter">Ajouter </a>
    </nav>
  </header>
  <main class="container-fluid">
    <?= $content; ?>
  </main>
  <footer class="bg-secondary p-3 text-center mt-3">
    &copy; - Hôtellerie - ILCI
  </footer>

  <script src="js/validation.js"></script>
  <script src="js/filtre.js"></script>
</body>
</html>
